# Starter code for a Maven CI/CD pipeline using GitHub Actions
name: Maven CI/CD Pipeline
on:
  push:
    branches:
      - workflow1
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Maven Build
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - run: mvn clean install